config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :groups, except: %i[ destroy index show] do
    resources :messages, only: %i[ index create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users_groups
  has_many :users, through: :users_groups
  accepts_nested_attributes_for :users_groups
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :body, presence: true

  def to_json
    { body: self[:body], user_name: self.user.name, time: self[:created_at].strftime("%Y/%m/%d %H:%M:%S") }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :users_groups
 has_many :messages
 has_many :groups, through: :users_groups
 accepts_nested_attributes_for :users_groups
end

app/models/users_group.rb
class UsersGroup < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  Time.zone = 'Asia/Tokyo'

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group, :set_current_groups, only: %i(edit update)

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group), notice: "チャットグループが編集されました。"
    else
      flash.now[:alert] = "チャットグループの作成に失敗しました。"
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: "チャットグループが編集されました。"
    else
      flash.now[:alert] ="チャットグループの編集に失敗しました。"
      render :new
    end
  end


  private

    def group_params
      params.require(:group).permit(:name, { user_ids: [] })
    end

    def set_group
      @group = Group.find(params[:id])
    end

    def set_current_groups
      @groups = current_user.groups
    end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_group, :set_group_users, :set_group_messages, :set_current_groups, :set_message

  def index
  end

  def create
    message = Message.new(create_params)
    respond_to do |format|
      if message.save
        new_message = message.to_json
        format.html { render :index}
        format.json { render json: new_message}
      else
        flash.now[:alert] = "メッセージ送信に失敗しました。"
        format.html { render :index}
        format.json { render json: false}
      end
    end
  end

  private

    def create_params
     params.require(:message).permit(:body).merge(group_id: params[:group_id], user_id: current_user.id)
    end

    def set_group
      @group = Group.find(params[:group_id])
    end

    def set_group_users
      set_group
      @group_users = @group.users
    end

    def set_group_messages
      set_group
      @group_messages = @group.messages
    end

    def set_current_groups
      @groups = current_user.groups
    end

    def set_message
      @message = Message.new
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

 def index
  @groups = current_user.groups
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_current_member.haml
%p.chat-group-user__name= current_member.name

app/views/groups/_group-left.haml
.chat-group-form__field--left
  =f.label :グループ名, class:'chat-group-form__label'

app/views/groups/_group.haml
= link_to group_messages_path(group) do
  %ul.lists
    %li.lists__group= group.name
    %li.lists__message
      = group.messages.last.try(:body)|| "まだメッセージはありません(°▽°)"

app/views/groups/_member-field.haml
.chat-group-form__field--left
  =f.label :チャットメンバーを追加, class:'chat-group-form__label'
.chat-group-form__field--right
  .chat-group-form__search.clearfix
    =f.collection_check_boxes :user_ids, User.all, :id, :name do |b|
      -b.label{b.check_box + b.text}
  #user-search-result

app/views/groups/_send-button.haml
.chat-group-form__field.clearfix
  .chat-group-form__field--left
  .chat-group-form__field--right
    %input.chat-group-form__action-btn{"data-disable-with" => "Save", :name => "commit", :type => "submit", :value => "Save"}/

app/views/groups/edit.haml
.chat-group-form
  %h1 チャットグループ編集
  #edit_chat_group_22.edit_chat_group
  =form_for @group do |f|
    .chat-group-form__field.clearfix
      =render partial: 'group-left', locals:{f: f}
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力して下さい",value: current_user.groups.first.name,class: 'chat-group-form__input', id: 'chat_group_name'
    .chat-group-form__field.clearfix
      =render partial: 'member-field',locals:{f: f}
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        -@current_members = current_user.groups.first.users
        =render partial: 'current_member', collection: @current_members
    =render partial: 'send-button'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  #edit_chat_group_22.edit_chat_group
  =form_for @group do |f|
    .chat-group-form__field.clearfix
      =render partial: 'group-left', locals:{f: f}
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力して下さい",value: current_user.groups.first.name,class: 'chat-group-form__input', id: 'chat_group_name'
    .chat-group-form__field.clearfix
      =render partial: 'member-field',locals:{f: f}
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        -@current_members = current_user.groups.first.users
        =render partial: 'current_member', collection: @current_members
    =render partial: 'send-button'

app/views/groups/new.haml
.wrapper
  .chat-group-form
    %h1 新規チャットグループ
    #new_chat_group.new_chat_group
    = form_for @group do |f|
      .chat-group-form__field.clearfix
        =render partial: 'group-left', locals:{f: f}
        .chat-group-form__field--right
          = f.text_field :name, placeholder: "グループ名を入力して下さい", class: 'chat-group-form__input', id: 'chat_group_name'
      .chat-group-form__field.clearfix
        =render partial: 'member-field', locals:{f: f}
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
          =f.label :チャットメンバー, for: "chat_group_チャットメンバー", class: 'chat-group-form__label'
        .chat-group-form__field--right
          #chat-group-users
            #chat-group-user-22.chat-group-user.clearfix
              %input{:name => "chat_group[user_ids][]", :type => "hidden", :value => "22"}/
              %p.chat-group-user__name= current_user.name
      =render partial: 'send-button'

app/views/groups/new.html.haml
.wrapper
  .chat-group-form
    %h1 新規チャットグループ
    #new_chat_group.new_chat_group
    = form_for @group do |f|
      .chat-group-form__field.clearfix
        =render partial: 'group-left', locals:{f: f}
        .chat-group-form__field--right
          = f.text_field :name, placeholder: "グループ名を入力して下さい", class: 'chat-group-form__input', id: 'chat_group_name'
      .chat-group-form__field.clearfix
        =render partial: 'member-field', locals:{f: f}
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
          =f.label :チャットメンバー, for: "chat_group_チャットメンバー", class: 'chat-group-form__label'
        .chat-group-form__field--right
          #chat-group-users
            #chat-group-user-22.chat-group-user.clearfix
              %input{:name => "chat_group[user_ids][]", :type => "hidden", :value => "22"}/
              %p.chat-group-user__name= current_user.name
      =render partial: 'send-button'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  -if notice
    %p.alert.alert-notice= notice
  -if alert
    %p.alert.alert-error= alert
  %body

  = yield

app/views/messages/_group_message.haml
%li.body
  .name-date
    .name-date__name=group_message.user.name
    .name-date__date=group_message.created_at.strftime("%Y/%m/%d %H:%M:%S")
  .message=group_message.body

app/views/messages/_group_user.haml
%li.header-right__member= group_user.name

app/views/messages/index.haml
%header

  %ul.header-right
    %li.header-right__current-group= @group.name
    %span.header-right__head member :
    =render partial: 'group_user', collection: @group_users
    =link_to edit_group_path(@group) do
      %ul.header-right__editbox
        %li.header-right__editbox__edit Edit
  =render partial: '/users/header_user'
.right-content
  %ul.chat_message
    =render partial: 'group_message', collection: @group_messages
.left-content
  =render @groups
%footer
  = form_for @message, url: { action: :create}, class: 'message_form' do |f|
    .text-box
      =f.text_area :body, cols: "30", placeholder: "type a message",rows: "16", class: 'message_area'
      %i.fa.fa-file-image-o.fa-2x
    .send-box
      =f.submit "Send",class: 'send-box__button'

app/views/users/_header_user.haml
%ul.header-user
  %li.header-user__name= current_user.name
  = link_to new_group_path do
    %i.fa.fa-pencil-square-o
  = link_to edit_user_registration_path do
    %i.fa.fa-cog

app/views/users/index.haml
%header
  =render partial: 'header_user'
.left-content
  =render @groups